version: '3.8'

services:
  fractol:
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    image: fractol:latest
    container_name: fractol
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/app
    network_mode: host
    stdin_open: true
    tty: true
    command: ./fractol mandelbrot
